server:
  port: 8088
spring:
  profiles:
    active: dev
  banner:
    location: ["classpath:banner.txt", "file:./banner.txt"]
  freemarker:
    cache: false
    settings:
      template_exception_handler: rethrow
      number_format: 0.##
    template-loader-path: ["classpath:/templates/", "file:./templates/"]
  messages:
    basename: i18n/message

  resources:
#    static-locations: ["classpath:static/", "file:./static/"]
#    static-locations: ["file:/Users/zhangboqing/data"]
#  mvc:
#    static-path-pattern: "/**"

# 配置mapper.xml位置，这个位置可以在pom.xml里配置
mybatis-plus:
  mapper-locations: classpath:/*Mapper.xml
